# Generated by Django 5.0.4 on 2024-05-25 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_old_cart_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 25, 16, 29, 20, 579450, tzinfo=datetime.timezone.utc)),
        ),
    ]
